name: CI 
on:
  push:
env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  #UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2019.4.13f1
jobs:
  build:
    #needs: [checklicense]
    #if: needs.checklicense.outputs.is_unity_license_set == 'true'    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          lfs: true
      - uses: actions/cache@v2.1.2
        with:
          path: Library
          key: Library          
      - uses: ryankurte/action-apt@v0.2.0
        with: 
          packages: "libc6-dev libncurses5"
      - name: Unity - Builder
        uses: webbertakken/unity-builder@v2.0-alpha-2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: Android
      # Output
      - uses: actions/upload-artifact@v2.2.0
        with:
          name: Build
          path: build